### ISSUE TITLE
My results

### ISSUE THREAD

**Issue by prince6show** [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing#10]
C=1            |                          Scale
                       1.0     |    1.4    |   1.8    |   2.2     |    2.6    | Mean
dev   EER    | 0.0752 | 0.1075 | 0.1341 | 0.1418 | 0.0681 | 0.1053
test   HTER | 0.1474 | 0.1242 | 0.1337 | 0.1368 | 0.1571 | 0.1131
test   EER    | 0.1100 | 0.1022 | 0.1082 | 0.1223 | 0.1457 | 0.1177

**Comment by prince6show** [comment]
@mnikitin Excuse me! I do not know why the dev eer is contrary to your results.

**Comment by mnikitin** [comment]
@prince6show Hello! 
If you didn't change the code semantically, the only possible reason is that you and I are using different face detectors, and yours one has more detection mistakes than mine. 
You can visualize wrongly classified frames and check whether face bboxes are correct or not.

**Comment by prince6show** [comment]
@mnikitin Thanks! I didn't change the code  and the face detectors I used https://blog.csdn.net/James_Ray_Murphy/article/details/79209172.  Could you tell me how to visualize wrongly classified frames?

**Comment by mnikitin** [comment]
@prince6show 
You need to take some threshold (e.g. dev-EER threshold, which you get in this line: https://github.com/mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing/blob/master/start_test.py#L124), and after that compute svm scores for some samples (dev or test). Compare the scores with the threshold, and with the help of ground truth labels (real or spoof), you can conclude, if sample was classified correctly.
For further analysis you might want to visualize those examples, with facial detection bboxes on them (=draw rectangle on the image and save it).

**Comment by prince6show** [comment]
@mnikitin Hi, I konw the reason. The face detectors I used can not detect the pictures of the spoofing videos. Could you give me the one you used? Thanks very much.

**Comment by mnikitin** [comment]
@prince6show sounds strange that your face detector can't find faces on the spoofing images. Such detectors are usually trained to detect faces without taking in consideration whether they are real or spoof. I think there should be some other problem with the usage of your detector.

Unfortunately, I can't provide you with the face detector I used, because it was the proprietary one. But there are many open-source implementations of face detectors. For example, you can use MT-CNN:
https://github.com/YYuanAnyVision/mxnet_mtcnn_face_detection
https://github.com/deepinsight/mxnet-mtcnn

**Comment by prince6show** [comment]
@mnikitin I get it.  Thanks a lot.

**Comment by sunjunlishi** [comment]
Do I have to use svm? I can get the result by using CNN getfeature directly

**Comment by mnikitin** [comment]
@sunjunlishi This repo is the implementation of the paper (https://arxiv.org/abs/1408.5601), where authors propose to use CNN features + SVM. 
Of course, in your own experiments you can use CNN prediction directly instead of SVM, but I didn't test it.

**Comment by sunjunlishi** [comment]
i meaning is use your cnn model directly。 your model can be used.it is ok.

**Comment by cploveflower** [comment]
Hello!
@prince6show 
I have known that you finished the procedure from the above question?can you tell me the procedure about the code?it's  very urgent for me!thank you very much

**Comment by cploveflower** [comment]
hello！
@prince6show 
whether  do you run the code in the linux？ I run it in the windows,but when I run it in the start_train.py ,it show some question :
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x000002D78EEB5EA0>
Traceback (most recent call last):
  File "C:\Users\cpp\AppData\Local\Programs\Python\Python35\lib\weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
do you know why about it,thank you1
