### ISSUE TITLE
Unable to Download CASIA-FASD Dataset

### ISSUE THREAD

**Issue by Mayureshdindorkar** [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing#13]
Can you please tell me the steps for downloading CASIA-FASD Dataset.

**Comment by mnikitin** [comment]
Already answered here: https://github.com/mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing/issues/3

**Comment by Mayureshdindorkar** [comment]
But I am unable to upload that EULA agreement on this link provided in that agreement :
http://www.cbsr.ia.ac.cn/images/xyz/AgreementUpload.aspx
It gives error as unable to submit.
Does it requires login & password?
Please tell....

**Comment by Mayureshdindorkar** [comment]
But I am unable to upload that EULA agreement on this link provided in that agreement :
http://www.cbsr.ia.ac.cn/images/xyz/AgreementUpload.aspx
It gives error as unable to submit.
Does it requires login & password?
Please tell....
