### ISSUE TITLE
CASIA-FASD EULA Agreement Link failure

### ISSUE THREAD

**Issue by Mayureshdindorkar** [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing#14]
But I am unable to upload that EULA agreement on this link provided in that agreement :
http://www.cbsr.ia.ac.cn/images/xyz/AgreementUpload.aspx
It gives error as unable to submit.
Does it requires login & password?
Please tell....

**Comment by mnikitin** [comment]
Well, it really looks like there are some issues with agreement submission.
I would recommend you to email directly to the authors of [original paper](http://www.cbsr.ia.ac.cn/users/zlei/papers/ICB2012/ZHANG-ICB2012.pdf) where CASIA-FASD was presenet, describe your problem and request dataset.
