### ISSUE TITLE
cannot run crop_image.py

### ISSUE THREAD

**Issue by loralin** [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing#2]
When i am running this py file, it has some problems.

**Comment by loralin** [comment]
It seems running, but i cannot get any changes or pictures, and even not errors.
![image](https://user-images.githubusercontent.com/39112629/39796657-386bdeea-539b-11e8-98ad-4550f40f749d.png)

**Comment by mnikitin** [comment]
Hello, @loralin !

Sorry, some scripts in this repo are still not very clearly documented. I will fix it some day :)

As for your question, this _crop_images.py_ script is supposed to be used for preparing face images (crop face area and resize) for subsequent training. In current implementation there is an assumption that you already have frames and face bboxes for each video, which are stored with the following structure (e.g. for _casia/train_release/15/HR_3.avi_):
_db_dir + 'train_release/15/HR_3/frames'_ -- directory with video frames in *.jpg format,
_db_dir + 'train_release/15/HR_3/bboxes'_ -- directory with face bboxes stored in *.txt format.
For each _frames/XXX.jpg_ image there should be corresponding _bboxes/XXX.txt_ file with face area coordinates.
It was the most convenient way of storing data when I conducted experiments with casia. You can easily modify this script in the way you want.
