### ISSUE TITLE
can not dowload the CASIA dataset

### ISSUE THREAD

**Issue by kvnzhao** [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing#3]
hello, can you share the method that how to dowload the CASIA dataset? I didn't find useful links to download the dataset. Thanks.

**Comment by xiaofateng** [comment]
the same question to kvnzhao, thanks

**Comment by mnikitin** [comment]
Hello guys @kvnzhao @xiaofateng !
You or your scientific supervisor should fill out and upload this agreement: http://www.cbsr.ia.ac.cn/english/FASDB_Agreement/Agreement.pdf .
After that you will get the access for CASIA-FASD downloading.
