### ISSUE TITLE
How i  can get the Casia Fasd ?

### ISSUE THREAD

**Issue by cploveflower** [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing#5]
Hello,i am a newer ,i want to know how can i get the CASIA dataset,I use the emil from my teacher ,but it still authenticate fail,can you give me a suggestion or give me the dataset?

**Comment by mnikitin** [comment]
Hi @cploveflower !
You (or your superviser) should fill out and upload that agreement http://www.cbsr.ia.ac.cn/english/FASDB_Agreement/Agreement.pdf . 
After that you will get the access for CASIA-FASD downloading.

**Comment by ngoanpv** [comment]
@cploveflower  The link to get access CASIA-FASD is not available recently (failed when submit), Did you get it? Please share with me at ngoanlearning@gmail.com.

Thank you very much.

**Comment by Coderx7** [comment]
@ngoanpv  any luck on getting your hand on the CASIA-FASD dataset? 
You can download the datset from here : https://pan.baidu.com/s/15HyX7tizCCuwN9BKiV9_zA 
Password: h5un 
however, the labels are missing!

**Comment by ljeff97** [comment]
@Coderx7 thanks a  lot! any ideas on how to recover the labels?

**Comment by Coderx7** [comment]
@ljeff97 You need to manually label them. in each folder there are only 3 correct samples which are. `1.avi`, `2.avi` and `HR_1.avi` everything else is negative sample. 
Therefore the dataset is very imbalanced and you need to balance it yourslef (doesnt make any difference if you convert them into images or directly consume the video files.)

**Comment by amit2319** [comment]
@Coderx7 Can you share also an alternative link for the dataset.. Maybe Google Drive.

**Comment by younge529** [comment]
Can you share dataset with my e-mail or google drive? I cannot access to baidu

**Comment by younge529** [comment]
@Coderx7 Can you share dataset with my e-mail or google drive? I cannot access to baidu

**Comment by Coderx7** [comment]
@amit2319 @younge529  here you are  : https://mega.nz/file/9BFDiKqT#VLexsuFDZjoA97c1J_h9hInm8AG75h6kG-TUfm3hYwg

**Comment by younge529** [comment]
@Coderx7 I unpacked file in the link you sent, but there are only 12 videos..
Can I get a whole CAISA_FASD dataset?
Thank very much for your response.

**Comment by Coderx7** [comment]
That's the whole dataset, each individual has 12 video files. what were you expecting?

**Comment by younge529** [comment]
Oh I got it.
Thank you very much for sharing dataset! :)

I'm studying anti-spoofing in Korea university in Korea.
If you don't mind and if you have idiap replay attack dataset, Could you
share it with me?

Again, thank you for your response.

2020년 11월 11일 (수) 오후 3:59, Seyyed Hossein Hasanpour <
notifications@github.com>님이 작성:

**Comment by Coderx7** [comment]
@younge529 you need to request for that dataset yourself. it cant be distributed like this. 
the casia-fasd dataset is is simply too limited/unusable for any practical reasons. 
if you need to have a larger dataset, then have a look at Celeb Spoof dataset its a 70+GB of images, and you can readily download it. it beats the idap replay attack dataset as well.

**Comment by younge529** [comment]
Thank you for your advice:)

2020년 11월 12일 (목) 오후 10:21, Seyyed Hossein Hasanpour <
notifications@github.com>님이 작성:

**Comment by phamthienvuong98** [comment]
@ngoanpv hello bro :)

**Comment by akaGabarito** [comment]
Does anyone possess knowledge regarding the license of this dataset?
