### ISSUE TITLE
Question about the funtion: estimate_hter

### ISSUE THREAD

**Issue by taylover-pei** [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing#6]
You have done a great job. But I have a question about how to compute HTER. In your test code shown as blow: 
![image](https://user-images.githubusercontent.com/27360803/49495079-cf38e880-f89c-11e8-95b5-80a6e2909161.png)
As show in red rectangle, why do you use the 'thr' computed through the data_dev to compute the HTER belong to the data_test? 
The standard function of HTER is below:
 
![image](https://user-images.githubusercontent.com/27360803/49495191-335bac80-f89d-11e8-9bea-816e53af92e2.png)
How to determine the threshold?
Thank you very much! 
Looking forward to your reply!

**Comment by mnikitin** [comment]
Hi @taylover-pei ! Thanks, I really appreciate your attention :)

As for HTER computation, here I've used the protocol which was described in the original paper (see https://arxiv.org/pdf/1408.5601.pdf, section IV.C).
It computes equal error rate (EER) threshold using dev set and then uses that threshold to compute half total error rate (HTER) for test dataset.

As far as I know, it is a standard approach for scalar HTER estimation.
