### ISSUE TITLE
Question about the code: start_test.py #7 

### ISSUE THREAD

**Issue by prince6show** [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing#9]
ValueError: Cannot find output that matches name "pooling2_output"
    net_output = 'pooling2_output' in line 20
Where the pooling2_output exists in？

**Comment by prince6show** [comment]
line 22, in load_net
    output_sym = sym.get_internals()[net_output]

**Comment by mnikitin** [comment]
Hi @prince6show !
'pooling2_output' exists in saved (trained) model. load_net() is in start_test.py script, which assumes you already trained CNNs for real/fake classification.
This repo doesn't contain pretrained models, so before using start_test, you firstly need to train some model(s).

**Comment by prince6show** [comment]
I already trained CNNs for real/fake classification, but there is no 'pooling2_output' in the sym.

**Comment by prince6show** [comment]
https://pan.baidu.com/s/1Y006TfQxh6kHudL2ABv1jQ

**Comment by mnikitin** [comment]
@prince6show did you use alexnet architecture from utils/net_generator.py for your CNN?
If so, 'pooling2_output' should exist in your sym, and it corresponds to the output of the 3rd pooling, right before the fully connected layers: https://github.com/mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing/blob/master/utils/net_generator.py#L25 .
In case you used your own architecture, or changed layer names, you need accordingly change the value of net_output.

If it doesn't help, could you please provide the list of all symbol names you have in sym.get_internals() ?

**Comment by prince6show** [comment]
Yes, I did.I did not change layer names and  the sym in the picture above.

**Comment by prince6show** [comment]
There is data、some conv1 and only one pooling3 in the  sym.get_internals().

**Comment by prince6show** [comment]
<Symbol group [data, conv1_weight, conv1_bias, conv1, activation7, lrn2, pooling3, conv2_weight, conv2_bias, conv2, activation8, lrn3, pooling4, conv3_weight, conv3_bias, conv3, activation9, conv4_weight, conv4_bias, conv4, activation10, conv5_weight, conv5_bias, conv5, activation11, pooling5, flatten1, fc1_weight, fc1_bias, fc1, activation12, dropout2, fc2_weight, fc2_bias, fc2, activation13, dropout3, fc3_weight, fc3_bias, fc3, softmax_label, softmax]>

**Comment by prince6show** [comment]
It changed.
<Symbol group [data, conv1_weight, conv1_bias, conv1, activation0, lrn0, pooling0, conv2_weight, conv2_bias, conv2, activation1, lrn1, pooling1, conv3_weight, conv3_bias, conv3, activation2, conv4_weight, conv4_bias, conv4, activation3, conv5_weight, conv5_bias, conv5, activation4, pooling2, flatten0, fc1_weight, fc1_bias, fc1, activation5, dropout0, fc2_weight, fc2_bias, fc2, activation6, dropout1, fc3_weight, fc3_bias, fc3, softmax_label, softmax]>

**Comment by prince6show** [comment]
"D:\Program Files\Anaconda3\python.exe" F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py
Scale: 1.0; Fold: 1. Preparing CNN features ...
[16:32:53] c:\jenkins\workspace\mxnet\mxnet\src\operator\nn\cudnn\./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.000977 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.003906 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.015625 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.062500 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.250000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=1.000000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=4.000000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=16.000000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=64.000000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=256.000000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=1024.000000 ...
Traceback (most recent call last):
  File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 143, in <module>
    test_net_casia('data/casia/CA_scale1', 'experiments/casia', 5, svm_c)
  File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 117, in test_net_casia
    net, mean = load_net(experiments_dir + '/' + experiment_str)
  File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 22, in load_net
    output_sym = sym.get_internals()[net_output]
  File "D:\Program Files\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py", line 520, in __getitem__
    raise ValueError('Cannot find output that matches name \"%s\"' % index)
ValueError: Cannot find output that matches name "pooling2_output"

**Comment by prince6show** [comment]
It do not work when k=2.

**Comment by prince6show** [comment]
@mnikitin I am puzzled that it doernot work when k=4 .

**Comment by prince6show** [comment]
@mnikitin It is absurd.
Scale: 1.0; Fold: 1. Preparing CNN features ...
[10:50:34] c:\jenkins\workspace\mxnet\mxnet\src\operator\nn\cudnn\./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.000977 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.003906 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.015625 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.062500 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.250000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=1.000000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=4.000000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=16.000000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=64.000000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=256.000000 ...
Scale: 1.0; Fold: 1. Training and estimation SVM with C=1024.000000 ...
Traceback (most recent call last):
  File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 143, in <module>
    test_net_casia('data/casia/CA_scale1', 'experiments/casia/CA_scale1', 5, svm_c)
  File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 117, in test_net_casia
    net, mean = load_net(experiments_dir + '/' + experiment_str)
  File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 22, in load_net
    output_sym = sym.get_internals()[net_output]
  File "D:\Program Files\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py", line 520, in __getitem__
    raise ValueError('Cannot find output that matches name \"%s\"' % index)
ValueError: Cannot find output that matches name "pooling2_output"

Process finished with exit code 1

**Comment by prince6show** [comment]
@mnikitin 
Question about the code: stastics.py
In 29, the value in thresholds is the same.
min_dist_stats = []

**Comment by prince6show** [comment]
Scale: 1.0; Fold: 1. Preparing CNN features ...
[12:04:41] c:\jenkins\workspace\mxnet\mxnet\src\operator\nn\cudnn\./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.000977 ...
Traceback (most recent call last):
  File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 143, in <module>
    test_net_casia('data/casia/CA_scales', 'experiments/casia/CA_scales', 5, svm_c)
  File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 131, in test_net_casia
    cur_eer_dev, thr = estimate_eer(data_dev, labels_dev, model)
  File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 71, in estimate_eer
    eer, thr = get_eer_stats(scores, labels)
  File "F:\DeepLearning\FaceAntiSpoofing\LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing\utils\statistics.py", line 37, in get_eer_stats
    eer = (min_dist_stats[0] + min_dist_stats[1]) / 2.0
IndexError: list index out of range

Process finished with exit code 1

**Comment by mnikitin** [comment]
> Scale: 1.0; Fold: 1. Preparing CNN features ...
> [12:04:41] c:\jenkins\workspace\mxnet\mxnet\src\operator\nn\cudnn./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
> Scale: 1.0; Fold: 1. Training and estimation SVM with C=0.000977 ...
> Traceback (most recent call last):
> File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 143, in 
> test_net_casia('data/casia/CA_scales', 'experiments/casia/CA_scales', 5, svm_c)
> File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 131, in test_net_casia
> cur_eer_dev, thr = estimate_eer(data_dev, labels_dev, model)
> File "F:/DeepLearning/FaceAntiSpoofing/LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing/start_test.py", line 71, in estimate_eer
> eer, thr = get_eer_stats(scores, labels)
> File "F:\DeepLearning\FaceAntiSpoofing\LearnConvolutionalNeuralNetworkforFaceAnti-Spoofing\utils\statistics.py", line 37, in get_eer_stats
> eer = (min_dist_stats[0] + min_dist_stats[1]) / 2.0
> IndexError: list index out of range
> 
> Process finished with exit code 1

Such error could arise only in case your 'scores' list is empty, which means there are still some problems with scores computation.

**Comment by prince6show** [comment]
The scores' list is not empty but the value in it are the same.

**Comment by prince6show** [comment]
@mnikitin Sometimes there are all identical value in the  'scores' list .

**Comment by ifcoxs** [comment]
@prince6show How did you convert the video into the corresponding frame picture? After I converted, there were always uncaligned pictures clipped.

**Comment by prince6show** [comment]
@ifcoxs https://blog.csdn.net/u010167269/article/details/53268686

**Comment by prince6show** [comment]
net_output = 'pooling2_output' Why ？？？why not fc2

**Comment by mnikitin** [comment]
@prince6show hello! I've already answered this question here:
https://github.com/mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing/issues/10#issuecomment-474015526
